import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { unified } from '@astrojs/markdown-remark';
import starlightLinksValidator from 'starlight-links-validator';
import {
  remarkRelativeMdLinks,
  starlightPreset,
} from '@syntax-syllogism/docs-theme';
import { fileURLToPath } from 'node:url';

const BASE = '/warden/docs';
const DOCS_ROOT = fileURLToPath(new URL('../docs', import.meta.url));

export default defineConfig({
  site: 'https://syntax-syllogism.com',
  base: BASE,
  outDir: './dist',
  trailingSlash: 'always',
  markdown: {
    processor: unified({
      remarkPlugins: [[remarkRelativeMdLinks, { base: BASE, docsRoot: DOCS_ROOT }]],
    }),
  },
  integrations: [
    starlight({
      ...starlightPreset({
        title: 'Warden',
        base: BASE,
        toolSlug: 'warden',
        publicRepo: 'Syntax-Syllogism/warden',
      }),
      // Explicit and flat. Starlight's default autogenerated sidebar groups by
      // `filePath` relative to `srcDir`, and the docs live outside it, so the
      // pages end up nested under `..` › `docs`. Order follows docs/README.md.
      sidebar: [
        'index',
        'getting-started',
        'command-details',
        'access-audits',
        'user-matching',
        'lifecycle-output',
        'output-contract',
      ],
    }),
    starlightLinksValidator(),
  ],
});
